# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dim_movie',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='movie_id')),
                ('movie_name', models.TextField(blank=True, max_length=100, verbose_name='movie_name')),
            ],
            options={
                'managed': True,
                'db_table': 'DimMovie',
            },
        ),
    ]
