# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dim_city',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='city_id')),
                ('city', models.TextField(blank=True, max_length=100, null=True, verbose_name='city')),
            ],
            options={
                'db_table': 'DimCity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='dim_genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='genre_id')),
                ('genre', models.TextField(blank=True, max_length=100, null=True, verbose_name='genre')),
            ],
            options={
                'db_table': 'DimGenre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='movie_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateTimeField(db_column='release_date', null=True)),
                ('city_fk', models.ForeignKey(db_column='city_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_fk', to='movie_digest.dim_city')),
                ('genre_fk', models.ForeignKey(db_column='genre_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_fk', to='movie_digest.dim_genre')),
            ],
            options={
                'db_table': 'MovieDetails',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='dim_movie',
            name='movie_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='movie_name'),
        ),
        migrations.AddField(
            model_name='movie_details',
            name='movie_fk',
            field=models.ForeignKey(db_column='movie_fk', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie_fk', to='movie_digest.dim_movie'),
        ),
    ]
