# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0002_auto_20190410_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dim_movie',
            old_name='movie_name',
            new_name='movie',
        ),
    ]
