# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0003_auto_20190410_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='movie_director',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='movie_director'),
        ),
        migrations.AddField(
            model_name='movie_details',
            name='movie_run_time',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='movie_run_time'),
        ),
    ]
