# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0004_auto_20190410_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie_details',
            name='movie_run_time',
        ),
        migrations.AddField(
            model_name='movie_details',
            name='movie_length',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='movie_length'),
        ),
    ]
