# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0005_auto_20190410_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dim_movie',
            name='movie',
            field=models.TextField(max_length=100, null=True, verbose_name='movie_name'),
        ),
    ]
