# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-04-10 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_digest', '0006_auto_20190410_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie_details',
            unique_together=set([('movie_fk', 'city_fk', 'release_date')]),
        ),
    ]
